import { Data } from "effect"

/** Engine failure codes whose HTTP contract is reviewed and safe to expose. */
export const HYDRA_ENGINE_ERROR_CODES = [
  "idempotency_conflict",
  "write_conflict",
  "writer_unavailable",
  "writer_lease_unavailable",
  "object_store_unavailable"
] as const

/** A stable, machine-actionable HydraDB engine failure code. */
export type HydraEngineErrorCode = (typeof HYDRA_ENGINE_ERROR_CODES)[number]

/**
 * A reviewed engine failure returned with its stable code and HTTP status.
 *
 * `reason` is deliberately generated by this client instead of copied from the
 * wire. This keeps an unexpected proxy/backend response from smuggling storage
 * or request details into logs, receipts, or user-visible errors.
 */
export class HydraEngineError extends Data.TaggedError("HydraEngineError")<{
  readonly code: HydraEngineErrorCode
  readonly status: number
  readonly query: string
  readonly retryable: boolean
  readonly reason: string
}> {
  override get message(): string {
    return `HydraDB engine failure (${this.code}): ${this.reason}`
  }
}

/**
 * HydraDB's parse errors are precise — they name the exact rule you broke — so
 * they are carried through verbatim in `reason` rather than being reworded.
 */
export class HydraParseError extends Data.TaggedError("HydraParseError")<{
  readonly reason: string
  readonly code: string
  readonly query: string
}> {
  override get message(): string {
    return `HydraDB rejected the statement: ${this.reason}`
  }
}

/** A server-side cap was hit: body size, runtime, result vertices, rate limit. */
export class HydraLimitError extends Data.TaggedError("HydraLimitError")<{
  readonly reason: string
  readonly status: number
  readonly query: string
}> {
  override get message(): string {
    return `HydraDB refused the statement on a limit: ${this.reason}`
  }
}

/** Transport failure, 5xx, or an unparseable response. */
export class HydraUnavailable extends Data.TaggedError("HydraUnavailable")<{
  readonly reason: string
  readonly status?: number
  readonly cause?: unknown
}> {
  override get message(): string {
    return `HydraDB is unavailable: ${this.reason}`
  }
}

/** A lossy numeric graph id could not be proven to represent one full key. */
export class HydraIdentityIntegrityError extends Data.TaggedError("HydraIdentityIntegrityError")<{
  readonly kind: "relationship" | "vertex"
  readonly reason: "missingFullKey" | "numericCollision" | "numericMismatch"
  readonly numericId: number
  /** SHA-256 fingerprints only: no tenant/user key material may cross this seam. */
  readonly existingKeyFingerprint: string | null
  /** SHA-256 fingerprint of the requested or observed full key. */
  readonly requestedKeyFingerprint: string
}> {
  override get message(): string {
    return `Hydra ${this.kind} identity integrity failure: ${this.reason} for numeric id ${this.numericId}`
  }
}

export type HydraError =
  | HydraEngineError
  | HydraIdentityIntegrityError
  | HydraParseError
  | HydraLimitError
  | HydraUnavailable
